service: lite-businesses
frameworkVersion: "3"

useDotenv: true

custom:
  bundle:
    copyFiles: # Copy any additional files to the generated package
      - from: "./src/views/*" # Where the files are currently
        to:
          "./"
          # Where in the package should they go
    ignorePackages:
      - pg-native
    forceExclude:
      - "@sparticuz/chrome-aws-lambda" # Because it'll be provided through a Lambda Layer
      - puppeteer-core

provider:
  name: "aws"
  runtime: nodejs16.x
  stage: ${opt:stage, "dev"}
  region: us-east-1
  environment:
    DB_HOST: ${cf:lite-businesses-dev.Endpoint}
    JWT_SECRET: ${env:JWT_SECRET}

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  - ${file(./src/Auth/auth-functions.yml)}
  - ${file(./src/functions.yml)}

resources:
  # Database
  - ${file(./resources/database.yml)}

  # NOTIFICATION'S ROLE
  - ${file(./resources/mailing-role.yml)}
