Resources:
  LiteBusinesses:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: lite-businesses-dev
      DBName: ${env:DB_USERNAME}
      DBInstanceClass: db.t3.micro
      Engine: postgres
      AvailabilityZone: us-east-1a
      StorageType: gp2
      AllocatedStorage: "20"
      MasterUsername: ${env:DB_USERNAME}
      MasterUserPassword: ${env:DB_PASSWORD}
      MultiAZ: false
      DeletionProtection: false
      PubliclyAccessible: true
Outputs:
  InstanceId:
    Description: Database's instance indentifier
    Value:
      Ref: LiteBusinesses
  Endpoint:
    Description: Database's endpoint
    Value:
      Fn::GetAtt: [LiteBusinesses, Endpoint.Address]
  UserDB:
    Description: Database's MasterUsername
    Value: ${env:DB_USERNAME}
  DBName:
    Description: Database's Name
    Value: ${env:DB_USERNAME}
